package fr.univ_nantes.slightstone.model;

public enum TypeCible {
	AUCUNE,

	UNE,
	TOUS,
	UN_SERVITEUR,
	TOUS_SERVITEURS,
	
	HEROS_ALLIE,
	TOUS_ALLIES,
	UN_ALLIE,
	UN_SERVITEUR_ALLIE,
	TOUS_SERVITEURS_ALLIES,
	
	HEROS_ADVERSAIRE,
	TOUS_ADVERSAIRES,
	UN_ADVERSAIRE,
	UN_SERVITEUR_ADVERSE,
	TOUS_SERVITEURS_ADVERSES
}